apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: http-8081
spec:
  path: /
  port:
    targetPort: "8081"
  to:
    kind: Service
    name: component-sample-dec6-1
    weight: null
status: {}
